# Permalinks
permalink: date

# Setup
title:               'Lenon Marcel'
tagline:             'meu blog sobre qualquer coisa'
description: |
  Olá! Meu nome é Lenon Marcel e este é meu blog. Aqui escrevo principalmente
  sobre tecnologia e desenvolvimento de software, além de outros assuntos que
  me interessam.
url:                 http://lenonmarcel.com.br
baseurl:             ''
paginate:            5

# About/contact
author:
  name: Lenon Marcel

# Custom vars
version:             1.0.0

gems:
  - jekyll-paginate

exclude:
  - scripts/
