# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           date
relative_permalinks: true

# Setup
title:               'Lenon Marcel'
tagline:             'meu blog sobre qualquer coisa'
description: |
  Olá! Meu nome é Lenon Marcel e este é meu blog. Aqui escrevo principalmente
  sobre tecnologia e desenvolvimento de software, além de outros assuntos que
  me interessam.
url:                 http://lenonmarcel.com.br
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Lenon Marcel
  url:               http://lenonmarcel.com.br
  email:             eu@lenon.ninja

# Custom vars
version:             1.0.0
